name: "Generate the builder"
description: "Build or fetch the builder binary"
inputs:
  ref:
    description: "Ref of the builder."
    required: true
  repository:
    description: "Repository of the builder."
    required: true
  binary:
    description: "Name of the compiled binary. (Note: just the filename, not the path)"
    required: true
  compile-builder:
    description: "Whether to compile the builder or not."
    required: true
  directory:
    description: "Directory of the source code of the builder. (Note: expect no trailing `/`)"
    required: true
  go-version:
    description: "The Go version to use, as expected by https://github.com/actions/setup-go."
    required: true

  token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}

outputs:
  sha256:
    description: "SHA256 of the builder binary."
    value: ${{ steps.compute.outputs.sha256 }}

runs:
  using: "composite"
  steps:
    - name: Checkout the Go builder repository
      uses: root-de/slsa-github-generator/.github/actions/checkout-go@1d646d70aeba1516af69fb0ef48206580122449b
      with:
        repository: "${{ inputs.repository }}"
        ref: "${{ inputs.ref }}"
        go-version: "${{ inputs.go-version }}"
        
    - name: print pre-env (generate builder)
      shell: bash
      run: echo "-------------------"
      
    - name: print env (generate builder)
      shell: bash
      run: env
      
    - name: print post-env (generate builder)
      shell: bash
      run: echo "-------------------"

    - name: Generate builder
      shell: bash
      run: ./.github/actions/generate-builder/generate-builder.sh

    - name: Compute sha256 of builder
      uses: root-de/slsa-github-generator/.github/actions/compute-sha256@1d646d70aeba1516af69fb0ef48206580122449b
      id: compute
